/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gt.edu.miumg.helloworld.gui;

import gt.edu.miumg.helloworld.modelo.Mes;
import gt.edu.miumg.helloworld.modelo.Persona;
import java.time.Year;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author melgust
 */
public class JFramePersona extends javax.swing.JFrame {
    
    List<Mes> meses;
    List<Integer> edades = new ArrayList<>();
    List<Persona> personas = new ArrayList<>();
    int year;

    /**
     * Creates new form JFramePersona
     */
    public JFramePersona() {
        initComponents();
        year = Year.now().getValue();
    }
    
    public void crearMeses(int year) {
        meses = new ArrayList<>();
        meses.add(new Mes(1, 31));
        if (esBisiesto(year)) {
            meses.add(new Mes(1, 29));
        } else {
            meses.add(new Mes(1, 28));
        }
        meses.add(new Mes(3, 31));
        meses.add(new Mes(4, 30));
        meses.add(new Mes(5, 31));
        meses.add(new Mes(7, 31));
        meses.add(new Mes(8, 31));
        meses.add(new Mes(9, 30));
        meses.add(new Mes(10, 31));
        meses.add(new Mes(11, 30));
        meses.add(new Mes(12, 31));
    }
    
    public boolean esBisiesto(int anio) {
        return anio % 4 == 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbNombre = new javax.swing.JLabel();
        jTxtNombre = new javax.swing.JTextField();
        jlbApellido = new javax.swing.JLabel();
        jTxtApellido = new javax.swing.JTextField();
        jBtnGuardar = new javax.swing.JButton();
        jBtnLimpiar = new javax.swing.JButton();
        jLblFechaNacimiento = new javax.swing.JLabel();
        jTxtFechaNacimiento = new javax.swing.JTextField();
        jLblCorreo = new javax.swing.JLabel();
        jTxtCorreo = new javax.swing.JTextField();
        jLblPeso = new javax.swing.JLabel();
        jTxtPeso = new javax.swing.JTextField();
        jTxtEstatura = new javax.swing.JTextField();
        jLblEstatura = new javax.swing.JLabel();
        jTxtEdad = new javax.swing.JTextField();
        jLblEdad = new javax.swing.JLabel();
        jLblEdades = new javax.swing.JLabel();
        Mostrar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Persona");

        jlbNombre.setText("Nombre");

        jlbApellido.setText("Apellido");

        jBtnGuardar.setText("Guardar");
        jBtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGuardarActionPerformed(evt);
            }
        });

        jBtnLimpiar.setText("Limpiar");
        jBtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLimpiarActionPerformed(evt);
            }
        });

        jLblFechaNacimiento.setText("Fecha nacimiento");

        jTxtFechaNacimiento.setText("dd/mm/yyyy");
        jTxtFechaNacimiento.setToolTipText("dd/mm/aaaa");
        jTxtFechaNacimiento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTxtFechaNacimientoFocusGained(evt);
            }
        });

        jLblCorreo.setText("Correo");

        jLblPeso.setText("Peso");

        jLblEstatura.setText("Estatura");

        jLblEdad.setText("Edad");

        jLblEdades.setText("Edades");

        Mostrar.setText("Mostrar");
        Mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem1.setText("jMenuItem1");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem2.setText("jMenuItem2");
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnLimpiar)
                        .addGap(69, 69, 69)
                        .addComponent(jLblEdades, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnGuardar)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jlbApellido)
                                    .addGap(446, 446, 446))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLblFechaNacimiento)
                                        .addComponent(jLblCorreo))
                                    .addGap(292, 292, 292))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLblPeso)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTxtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLblEdad)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTxtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(26, 26, 26)
                                    .addComponent(jLblEstatura)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTxtEstatura, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlbNombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTxtApellido)
                                        .addComponent(jTxtNombre)
                                        .addComponent(jTxtFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTxtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(79, 79, 79))))
            .addGroup(layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(Mostrar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlbNombre)
                        .addGap(29, 29, 29)
                        .addComponent(jlbApellido)
                        .addGap(30, 30, 30)
                        .addComponent(jLblFechaNacimiento))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jTxtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))
                    .addComponent(jTxtFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblCorreo)
                    .addComponent(jTxtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblPeso)
                    .addComponent(jTxtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblEstatura)
                    .addComponent(jTxtEstatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblEdad)
                    .addComponent(jTxtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnGuardar)
                    .addComponent(jBtnLimpiar)
                    .addComponent(jLblEdades))
                .addGap(18, 18, 18)
                .addComponent(Mostrar)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public boolean validarFecha(String fecha) {
        String partes[] = fecha.split("/");
        if (partes.length != 3) {
            return false;
        }
        int nmes = Integer.parseInt(partes[1].trim());
        int dia = Integer.parseInt(partes[0].trim());
        String strAnio = partes[2].trim();
        int anio = Integer.parseInt(strAnio);
        if (anio < 0) {
            return false;
        }
        if (anio > 0) {
            if (strAnio.length() == 1) {
                strAnio = "200" + strAnio;
            }
            if (strAnio.length() == 2) {
                strAnio = "20" + strAnio;
            }
            if (strAnio.length() == 3) {
                strAnio = "2" + strAnio;
            }
        }
        anio = Integer.parseInt(strAnio);
        if (anio > year) {
            return false;
        }
        crearMeses(anio);
        if (nmes < 1 || nmes > 12) {
            return false;
        }
        Mes mes = null;
        for (Mes mes2 : meses) {
            if (mes2.getNumero() == nmes) {
                mes = mes2;
            }
        }
        if (dia < 1 || dia > mes.getDias()) {
            return false;
        }
        return true;
    }
    
    private boolean validarCampo(JTextField campo) {
        String texto = campo.getText();
        if (texto == null) {
            return false;
        }
        if (texto.isBlank()) {
            return false;
        }
        return true;
    }
    
    private void mostrarError(String mensaje, String titulo) {
        JOptionPane.showMessageDialog(this, mensaje, titulo, JOptionPane.ERROR_MESSAGE);
    }
    
    private void jBtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGuardarActionPerformed
        // TODO add your handling code here:
        /*if (!validarCampo(jTxtNombre)) {
            mostrarError("Debe ingresar un nombre", "Error en datos");
        }
        if (!validarCampo(jTxtCorreo)) {
            mostrarError("Debe ingresar un correo", "Error en datos");
        }
        if (!validarCampo(jTxtApellido)) {
            mostrarError("Debe ingresar un apellido", "Error en datos");
        }
        if (!validarCampo(jTxtFechaNacimiento) || !validarFecha(jTxtFechaNacimiento.getText())) {
            mostrarError("Debe ingresar una fecha de nacimiento", "Error en datos");
        }*/
        if (!validarCampo(jTxtEdad)) {
            mostrarError("Debe ingresar una edad", "Error en datos");
        }
        edades.add(Integer.valueOf(jTxtEdad.getText().trim()));
        jTxtEdad.setText("");
        jTxtEstatura.setText(String.valueOf(edades.size()));
    }//GEN-LAST:event_jBtnGuardarActionPerformed

    private void jBtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLimpiarActionPerformed
        // TODO add your handling code here:
        jTxtNombre.setText("");
        jTxtApellido.setText("");
        String strEdades = "";
        for (Integer edad : edades) {
            strEdades += edad + ", ";
        }
        jLblEdades.setText("Edades: " + strEdades);
    }//GEN-LAST:event_jBtnLimpiarActionPerformed

    private void jTxtFechaNacimientoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtFechaNacimientoFocusGained
        // TODO add your handling code here:
        jTxtFechaNacimiento.setText("");
    }//GEN-LAST:event_jTxtFechaNacimientoFocusGained

    private void MostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MostrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePersona().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Mostrar;
    private javax.swing.JButton jBtnGuardar;
    private javax.swing.JButton jBtnLimpiar;
    private javax.swing.JLabel jLblCorreo;
    private javax.swing.JLabel jLblEdad;
    private javax.swing.JLabel jLblEdades;
    private javax.swing.JLabel jLblEstatura;
    private javax.swing.JLabel jLblFechaNacimiento;
    private javax.swing.JLabel jLblPeso;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JTextField jTxtApellido;
    private javax.swing.JTextField jTxtCorreo;
    private javax.swing.JTextField jTxtEdad;
    private javax.swing.JTextField jTxtEstatura;
    private javax.swing.JTextField jTxtFechaNacimiento;
    private javax.swing.JTextField jTxtNombre;
    private javax.swing.JTextField jTxtPeso;
    private javax.swing.JLabel jlbApellido;
    private javax.swing.JLabel jlbNombre;
    // End of variables declaration//GEN-END:variables
}
